# AI Provider Configuration Template
# Copy this file to ai_config.yaml and add your actual API keys
# DO NOT commit ai_config.yaml to version control

# API Keys (replace with your actual keys)
anthropic_api_key: null  # Get from: https://console.anthropic.com/settings/keys
openai_api_key: null     # Get from: https://platform.openai.com/api-keys

# Model Configuration for Anthropic Claude
anthropic:
  model: "claude-3-5-sonnet-20241022"  # Options: claude-3-5-sonnet, claude-3-haiku, claude-3-opus
  max_tokens: 1000
  temperature: 0.7
  max_history_length: 10

# Model Configuration for OpenAI ChatGPT  
openai:
  model: "gpt-3.5-turbo"  # Options: gpt-3.5-turbo, gpt-4, gpt-4-turbo
  max_tokens: 1000
  temperature: 0.7
  max_history_length: 10