ai:
  config_file: ai_config.yaml
  provider: anthropic
audio:
  chunk_size: 512
  sample_rate: 16000
speech:
  language: en-US
  recognition_engines:
  - google
  - vosk
  - sphinx
tts:
  rate: 150
  voice_id: com.apple.voice.compact.en-US.Samantha
  volume: 1.0
wake_word:
  name: TestAssistant
  sensitivity: 0.5
