audio:
  chunk_size: 512
  sample_rate: 16000
speech:
  language: en-US
  provider: vosk
wake_word:
  name: null
  sensitivity: 0.5
tts:
  voice_id: "com.apple.voice.compact.en-US.Samantha"
  rate: 150
  volume: 1.0
